apiVersion: v2
name: project-template
description: Multi-service project template with Flask, Go, and React
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Penguin Tech Inc
    email: support@penguintech.io
dependencies:
  - name: postgresql
    version: "~12"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "~17"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
