// Module is the plugin-side gRPC contract for external modules.
// It mirrors sdk.Module 1:1 across the go-plugin boundary.
// The plugin implements ModuleService; the daemon implements HostService.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.1
// source: pkg/sdk/proto/penguin/sdk/v1/module.proto

package sdkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModuleService_Info_FullMethodName         = "/penguin.sdk.v1.ModuleService/Info"
	ModuleService_Init_FullMethodName         = "/penguin.sdk.v1.ModuleService/Init"
	ModuleService_Start_FullMethodName        = "/penguin.sdk.v1.ModuleService/Start"
	ModuleService_Stop_FullMethodName         = "/penguin.sdk.v1.ModuleService/Stop"
	ModuleService_Status_FullMethodName       = "/penguin.sdk.v1.ModuleService/Status"
	ModuleService_Health_FullMethodName       = "/penguin.sdk.v1.ModuleService/Health"
	ModuleService_Commands_FullMethodName     = "/penguin.sdk.v1.ModuleService/Commands"
	ModuleService_Dispatch_FullMethodName     = "/penguin.sdk.v1.ModuleService/Dispatch"
	ModuleService_ConfigSchema_FullMethodName = "/penguin.sdk.v1.ModuleService/ConfigSchema"
)

// ModuleServiceClient is the client API for ModuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModuleService is the gRPC interface an external plugin implements.
// All request messages include api_version per PenguinTech gRPC standards.
// Unknown api_version → return UNIMPLEMENTED.
type ModuleServiceClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Commands(ctx context.Context, in *CommandsRequest, opts ...grpc.CallOption) (*CommandsResponse, error)
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
	ConfigSchema(ctx context.Context, in *ConfigSchemaRequest, opts ...grpc.CallOption) (*ConfigSchemaResponse, error)
}

type moduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModuleServiceClient(cc grpc.ClientConnInterface) ModuleServiceClient {
	return &moduleServiceClient{cc}
}

func (c *moduleServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, ModuleService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, ModuleService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, ModuleService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, ModuleService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ModuleService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ModuleService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Commands(ctx context.Context, in *CommandsRequest, opts ...grpc.CallOption) (*CommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandsResponse)
	err := c.cc.Invoke(ctx, ModuleService_Commands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, ModuleService_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) ConfigSchema(ctx context.Context, in *ConfigSchemaRequest, opts ...grpc.CallOption) (*ConfigSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigSchemaResponse)
	err := c.cc.Invoke(ctx, ModuleService_ConfigSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServiceServer is the server API for ModuleService service.
// All implementations must embed UnimplementedModuleServiceServer
// for forward compatibility.
//
// ModuleService is the gRPC interface an external plugin implements.
// All request messages include api_version per PenguinTech gRPC standards.
// Unknown api_version → return UNIMPLEMENTED.
type ModuleServiceServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	Init(context.Context, *InitRequest) (*InitResponse, error)
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Commands(context.Context, *CommandsRequest) (*CommandsResponse, error)
	Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error)
	ConfigSchema(context.Context, *ConfigSchemaRequest) (*ConfigSchemaResponse, error)
	mustEmbedUnimplementedModuleServiceServer()
}

// UnimplementedModuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModuleServiceServer struct{}

func (UnimplementedModuleServiceServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedModuleServiceServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedModuleServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedModuleServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedModuleServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedModuleServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedModuleServiceServer) Commands(context.Context, *CommandsRequest) (*CommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commands not implemented")
}
func (UnimplementedModuleServiceServer) Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedModuleServiceServer) ConfigSchema(context.Context, *ConfigSchemaRequest) (*ConfigSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigSchema not implemented")
}
func (UnimplementedModuleServiceServer) mustEmbedUnimplementedModuleServiceServer() {}
func (UnimplementedModuleServiceServer) testEmbeddedByValue()                       {}

// UnsafeModuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModuleServiceServer will
// result in compilation errors.
type UnsafeModuleServiceServer interface {
	mustEmbedUnimplementedModuleServiceServer()
}

func RegisterModuleServiceServer(s grpc.ServiceRegistrar, srv ModuleServiceServer) {
	// If the following call panics, it indicates UnimplementedModuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModuleService_ServiceDesc, srv)
}

func _ModuleService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Commands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Commands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Commands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Commands(ctx, req.(*CommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_ConfigSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).ConfigSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_ConfigSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).ConfigSchema(ctx, req.(*ConfigSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModuleService_ServiceDesc is the grpc.ServiceDesc for ModuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "penguin.sdk.v1.ModuleService",
	HandlerType: (*ModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _ModuleService_Info_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _ModuleService_Init_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _ModuleService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _ModuleService_Stop_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _ModuleService_Status_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ModuleService_Health_Handler,
		},
		{
			MethodName: "Commands",
			Handler:    _ModuleService_Commands_Handler,
		},
		{
			MethodName: "Dispatch",
			Handler:    _ModuleService_Dispatch_Handler,
		},
		{
			MethodName: "ConfigSchema",
			Handler:    _ModuleService_ConfigSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/sdk/proto/penguin/sdk/v1/module.proto",
}

const (
	HostService_Log_FullMethodName                   = "/penguin.sdk.v1.HostService/Log"
	HostService_SecretsGet_FullMethodName            = "/penguin.sdk.v1.HostService/SecretsGet"
	HostService_SecretsSet_FullMethodName            = "/penguin.sdk.v1.HostService/SecretsSet"
	HostService_SecretsDelete_FullMethodName         = "/penguin.sdk.v1.HostService/SecretsDelete"
	HostService_LicenseFeatureEnabled_FullMethodName = "/penguin.sdk.v1.HostService/LicenseFeatureEnabled"
	HostService_LicenseTier_FullMethodName           = "/penguin.sdk.v1.HostService/LicenseTier"
	HostService_DataDir_FullMethodName               = "/penguin.sdk.v1.HostService/DataDir"
	HostService_Config_FullMethodName                = "/penguin.sdk.v1.HostService/Config"
	HostService_PublishEvent_FullMethodName          = "/penguin.sdk.v1.HostService/PublishEvent"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostService is the reverse direction: the daemon serves this over go-plugin's
// gRPC broker so plugins can call back into daemon capabilities (logging, secrets,
// licensing, config, events).
type HostServiceClient interface {
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	SecretsGet(ctx context.Context, in *SecretsGetRequest, opts ...grpc.CallOption) (*SecretsGetResponse, error)
	SecretsSet(ctx context.Context, in *SecretsSetRequest, opts ...grpc.CallOption) (*SecretsSetResponse, error)
	SecretsDelete(ctx context.Context, in *SecretsDeleteRequest, opts ...grpc.CallOption) (*SecretsDeleteResponse, error)
	LicenseFeatureEnabled(ctx context.Context, in *LicenseFeatureEnabledRequest, opts ...grpc.CallOption) (*LicenseFeatureEnabledResponse, error)
	LicenseTier(ctx context.Context, in *LicenseTierRequest, opts ...grpc.CallOption) (*LicenseTierResponse, error)
	DataDir(ctx context.Context, in *DataDirRequest, opts ...grpc.CallOption) (*DataDirResponse, error)
	Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, HostService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) SecretsGet(ctx context.Context, in *SecretsGetRequest, opts ...grpc.CallOption) (*SecretsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretsGetResponse)
	err := c.cc.Invoke(ctx, HostService_SecretsGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) SecretsSet(ctx context.Context, in *SecretsSetRequest, opts ...grpc.CallOption) (*SecretsSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretsSetResponse)
	err := c.cc.Invoke(ctx, HostService_SecretsSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) SecretsDelete(ctx context.Context, in *SecretsDeleteRequest, opts ...grpc.CallOption) (*SecretsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretsDeleteResponse)
	err := c.cc.Invoke(ctx, HostService_SecretsDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) LicenseFeatureEnabled(ctx context.Context, in *LicenseFeatureEnabledRequest, opts ...grpc.CallOption) (*LicenseFeatureEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LicenseFeatureEnabledResponse)
	err := c.cc.Invoke(ctx, HostService_LicenseFeatureEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) LicenseTier(ctx context.Context, in *LicenseTierRequest, opts ...grpc.CallOption) (*LicenseTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LicenseTierResponse)
	err := c.cc.Invoke(ctx, HostService_LicenseTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) DataDir(ctx context.Context, in *DataDirRequest, opts ...grpc.CallOption) (*DataDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataDirResponse)
	err := c.cc.Invoke(ctx, HostService_DataDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, HostService_Config_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishEventResponse)
	err := c.cc.Invoke(ctx, HostService_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
//
// HostService is the reverse direction: the daemon serves this over go-plugin's
// gRPC broker so plugins can call back into daemon capabilities (logging, secrets,
// licensing, config, events).
type HostServiceServer interface {
	Log(context.Context, *LogRequest) (*LogResponse, error)
	SecretsGet(context.Context, *SecretsGetRequest) (*SecretsGetResponse, error)
	SecretsSet(context.Context, *SecretsSetRequest) (*SecretsSetResponse, error)
	SecretsDelete(context.Context, *SecretsDeleteRequest) (*SecretsDeleteResponse, error)
	LicenseFeatureEnabled(context.Context, *LicenseFeatureEnabledRequest) (*LicenseFeatureEnabledResponse, error)
	LicenseTier(context.Context, *LicenseTierRequest) (*LicenseTierResponse, error)
	DataDir(context.Context, *DataDirRequest) (*DataDirResponse, error)
	Config(context.Context, *ConfigRequest) (*ConfigResponse, error)
	PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServiceServer) SecretsGet(context.Context, *SecretsGetRequest) (*SecretsGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SecretsGet not implemented")
}
func (UnimplementedHostServiceServer) SecretsSet(context.Context, *SecretsSetRequest) (*SecretsSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SecretsSet not implemented")
}
func (UnimplementedHostServiceServer) SecretsDelete(context.Context, *SecretsDeleteRequest) (*SecretsDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SecretsDelete not implemented")
}
func (UnimplementedHostServiceServer) LicenseFeatureEnabled(context.Context, *LicenseFeatureEnabledRequest) (*LicenseFeatureEnabledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LicenseFeatureEnabled not implemented")
}
func (UnimplementedHostServiceServer) LicenseTier(context.Context, *LicenseTierRequest) (*LicenseTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LicenseTier not implemented")
}
func (UnimplementedHostServiceServer) DataDir(context.Context, *DataDirRequest) (*DataDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DataDir not implemented")
}
func (UnimplementedHostServiceServer) Config(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Config not implemented")
}
func (UnimplementedHostServiceServer) PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call panics, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_SecretsGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).SecretsGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_SecretsGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).SecretsGet(ctx, req.(*SecretsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_SecretsSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretsSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).SecretsSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_SecretsSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).SecretsSet(ctx, req.(*SecretsSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_SecretsDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).SecretsDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_SecretsDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).SecretsDelete(ctx, req.(*SecretsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_LicenseFeatureEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicenseFeatureEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).LicenseFeatureEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_LicenseFeatureEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).LicenseFeatureEnabled(ctx, req.(*LicenseFeatureEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_LicenseTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicenseTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).LicenseTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_LicenseTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).LicenseTier(ctx, req.(*LicenseTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_DataDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).DataDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_DataDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).DataDir(ctx, req.(*DataDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Config_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Config(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).PublishEvent(ctx, req.(*PublishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "penguin.sdk.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _HostService_Log_Handler,
		},
		{
			MethodName: "SecretsGet",
			Handler:    _HostService_SecretsGet_Handler,
		},
		{
			MethodName: "SecretsSet",
			Handler:    _HostService_SecretsSet_Handler,
		},
		{
			MethodName: "SecretsDelete",
			Handler:    _HostService_SecretsDelete_Handler,
		},
		{
			MethodName: "LicenseFeatureEnabled",
			Handler:    _HostService_LicenseFeatureEnabled_Handler,
		},
		{
			MethodName: "LicenseTier",
			Handler:    _HostService_LicenseTier_Handler,
		},
		{
			MethodName: "DataDir",
			Handler:    _HostService_DataDir_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _HostService_Config_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _HostService_PublishEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/sdk/proto/penguin/sdk/v1/module.proto",
}
