// Package modulepb defines the types used for module plugin communication.
// These types mirror the protobuf definitions in api/proto/module/v1/module.proto.
// In production, these would be generated by protoc; here they are hand-written
// for portability and to avoid a protoc build dependency.
package modulepb

// HealthState represents module health.
type HealthState int32

const (
	HealthUnknown   HealthState = 0
	HealthHealthy   HealthState = 1
	HealthDegraded  HealthState = 2
	HealthUnhealthy HealthState = 3
)

func (h HealthState) String() string {
	switch h {
	case HealthHealthy:
		return "healthy"
	case HealthDegraded:
		return "degraded"
	case HealthUnhealthy:
		return "unhealthy"
	default:
		return "unknown"
	}
}

// ModuleInfo describes a module's identity.
type ModuleInfo struct {
	Name        string
	DisplayName string
	Description string
	Version     string
}

// InitRequest carries initialization parameters to a plugin module.
type InitRequest struct {
	ConfigDir  string
	DataDir    string
	AuthToken  string
	LicenseKey string
	Extra      map[string]string
}

// InitResponse carries the result of module initialization.
type InitResponse struct {
	OK    bool
	Error string
}

// HealthCheckResponse carries health check results.
type HealthCheckResponse struct {
	State   HealthState
	Message string
	Details map[string]string
}

// WidgetType identifies the kind of declarative UI widget.
type WidgetType int32

const (
	WidgetLabel     WidgetType = 0
	WidgetButton    WidgetType = 1
	WidgetEntry     WidgetType = 2
	WidgetSelect    WidgetType = 3
	WidgetCard      WidgetType = 4
	WidgetVBox      WidgetType = 5
	WidgetHBox      WidgetType = 6
	WidgetSeparator WidgetType = 7
	WidgetScroll    WidgetType = 8
	WidgetCheckbox  WidgetType = 9
	WidgetRichText  WidgetType = 10
)

// Widget is a declarative UI node that describes a Fyne widget.
type Widget struct {
	Type       WidgetType
	ID         string
	Text       string
	Value      string
	Children   []*Widget
	Disabled   bool
	Options    []string
	Properties map[string]string
}

// GUIPanel wraps the root widget tree for a module's GUI.
type GUIPanel struct {
	Root *Widget
}

// GUIEvent represents a user interaction with a widget.
type GUIEvent struct {
	WidgetID  string
	EventType string // "tapped", "changed", "submitted"
	Value     string
}

// CLIFlag describes a CLI flag.
type CLIFlag struct {
	Name         string
	Shorthand    string
	Usage        string
	DefaultValue string
	Required     bool
}

// CLICommand describes a CLI command tree.
type CLICommand struct {
	Use         string
	Short       string
	Long        string
	Flags       []CLIFlag
	Subcommands []CLICommand
}

// CLICommandList wraps a list of top-level CLI commands.
type CLICommandList struct {
	Commands []CLICommand
}

// CLICommandRequest carries CLI execution parameters.
type CLICommandRequest struct {
	Args        []string
	Flags       map[string]string
	CommandPath string // e.g., "vpn connect"
}

// CLICommandResponse carries CLI execution results.
type CLICommandResponse struct {
	Stdout   string
	Stderr   string
	ExitCode int32
}

// IconResponse carries icon data.
type IconResponse struct {
	PNGData []byte
	Name    string
}
