//go:build linux
// +build linux

package squawk

import (
	"context"
	"fmt"
	"net/netip"
	"os"
	"path/filepath"
	"strings"
	"time"

	"go.uber.org/zap"
)

// resolvConfPath is the path to the system resolver configuration file.
// This is injected as a package-level seam for testing purposes.
var resolvConfPath = "/etc/resolv.conf"

// applyPlatform applies DNS servers on Linux using systemd-resolved (D-Bus) or /etc/resolv.conf.
func (r *resolver) applyPlatform(ctx context.Context, servers []netip.Addr) error {
	// Try systemd-resolved via D-Bus first
	if err := r.applyViaSystemdResolved(ctx, servers); err == nil {
		r.logger.Info("applied DNS via systemd-resolved")
		return nil
	}

	// Fallback to /etc/resolv.conf
	if err := r.applyViaResolvConf(servers); err != nil {
		return fmt.Errorf("apply via resolv.conf: %w", err)
	}

	r.logger.Info("applied DNS via /etc/resolv.conf")
	return nil
}

// restorePlatform restores DNS servers on Linux.
func (r *resolver) restorePlatform(ctx context.Context, servers []netip.Addr) error {
	// Try systemd-resolved first
	if err := r.restoreViaSystemdResolved(ctx, servers); err == nil {
		r.logger.Info("restored DNS via systemd-resolved")
		return nil
	}

	// Fallback to /etc/resolv.conf
	if err := r.restoreViaResolvConf(servers); err != nil {
		return fmt.Errorf("restore via resolv.conf: %w", err)
	}

	r.logger.Info("restored DNS via /etc/resolv.conf")
	return nil
}

// currentPlatform reads the current DNS servers on Linux.
func (r *resolver) currentPlatform(ctx context.Context) ([]netip.Addr, error) {
	// Try resolv.conf (path is injectable via resolvConfPath)
	content, err := os.ReadFile(resolvConfPath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", resolvConfPath, err)
	}

	var servers []netip.Addr
	for _, line := range strings.Split(string(content), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "nameserver ") {
			parts := strings.Fields(line)
			if len(parts) > 1 {
				if addr, err := netip.ParseAddr(parts[1]); err == nil {
					servers = append(servers, addr)
				}
			}
		}
	}

	if len(servers) == 0 {
		return nil, fmt.Errorf("no nameservers found in %s", resolvConfPath)
	}

	return servers, nil
}

// captureState captures the current resolver state for recovery.
func (r *resolver) captureState() string {
	content, err := os.ReadFile(resolvConfPath)
	if err != nil {
		return ""
	}
	return string(content)
}

// applyViaResolvConf applies DNS by writing to resolv.conf with backup.
func (r *resolver) applyViaResolvConf(servers []netip.Addr) error {
	// Backup existing resolv.conf
	backupPath := filepath.Join(r.dataDir, "resolv.conf.backup")
	if content, err := os.ReadFile(resolvConfPath); err == nil {
		// #nosec G703 - backupPath is constructed from dataDir which is controlled
		if err := os.WriteFile(backupPath, content, 0o600); err != nil {
			r.logger.Warn("failed to backup resolv.conf", zap.Error(err))
		}
	}

	// Generate new resolv.conf
	lines := make([]string, 0, 2+len(servers))
	lines = append(lines, "# Generated by penguin squawk module")
	for _, server := range servers {
		lines = append(lines, fmt.Sprintf("nameserver %s", server.String()))
	}
	lines = append(lines, "")

	newContent := strings.Join(lines, "\n")
	if err := os.WriteFile(resolvConfPath, []byte(newContent), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", resolvConfPath, err)
	}

	return nil
}

// restoreViaResolvConf restores DNS from backup.
func (r *resolver) restoreViaResolvConf(servers []netip.Addr) error {
	backupPath := filepath.Join(r.dataDir, "resolv.conf.backup")
	// #nosec G304 - backupPath is constructed from dataDir which is controlled
	content, err := os.ReadFile(backupPath)
	if err != nil {
		// No backup; use provided servers as fallback
		return r.applyViaResolvConf(servers)
	}

	// #nosec G703 - resolvConfPath is intentional (system DNS management is the feature)
	if err := os.WriteFile(resolvConfPath, content, 0o600); err != nil {
		return fmt.Errorf("restore %s: %w", resolvConfPath, err)
	}

	// Clean up backup
	_ = os.Remove(backupPath)
	return nil
}

func getCurrentUnixTime() int64 {
	return time.Now().Unix()
}
