// Daemon IPC contract between the penguin CLI / penguin-tray and penguind.
// Served over an authenticated local transport only (unix socket / named
// pipe) — never a network port.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: api/proto/penguin/daemon/v1/daemon.proto

package daemonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *VersionRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaemonVersion string                 `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *VersionResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *VersionResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type ListModulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesRequest) Reset() {
	*x = ListModulesRequest{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesRequest) ProtoMessage() {}

func (x *ListModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesRequest.ProtoReflect.Descriptor instead.
func (*ListModulesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *ListModulesRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type ModuleSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	State          string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`        // sdk.ModuleState string
	External       bool                   `protobuf:"varint,5,opt,name=external,proto3" json:"external,omitempty"` // true for verified external plugins
	LicenseFeature string                 `protobuf:"bytes,6,opt,name=license_feature,json=licenseFeature,proto3" json:"license_feature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModuleSummary) Reset() {
	*x = ModuleSummary{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleSummary) ProtoMessage() {}

func (x *ModuleSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleSummary.ProtoReflect.Descriptor instead.
func (*ModuleSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *ModuleSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleSummary) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModuleSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ModuleSummary) GetExternal() bool {
	if x != nil {
		return x.External
	}
	return false
}

func (x *ModuleSummary) GetLicenseFeature() string {
	if x != nil {
		return x.LicenseFeature
	}
	return ""
}

type ListModulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*ModuleSummary       `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesResponse) Reset() {
	*x = ListModulesResponse{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesResponse) ProtoMessage() {}

func (x *ListModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesResponse.ProtoReflect.Descriptor instead.
func (*ListModulesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *ListModulesResponse) GetModules() []*ModuleSummary {
	if x != nil {
		return x.Modules
	}
	return nil
}

type LoadModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModuleRequest) Reset() {
	*x = LoadModuleRequest{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModuleRequest) ProtoMessage() {}

func (x *LoadModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModuleRequest.ProtoReflect.Descriptor instead.
func (*LoadModuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *LoadModuleRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *LoadModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModuleResponse) Reset() {
	*x = LoadModuleResponse{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModuleResponse) ProtoMessage() {}

func (x *LoadModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModuleResponse.ProtoReflect.Descriptor instead.
func (*LoadModuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *LoadModuleResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type UnloadModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModuleRequest) Reset() {
	*x = UnloadModuleRequest{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModuleRequest) ProtoMessage() {}

func (x *UnloadModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModuleRequest.ProtoReflect.Descriptor instead.
func (*UnloadModuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *UnloadModuleRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *UnloadModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UnloadModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModuleResponse) Reset() {
	*x = UnloadModuleResponse{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModuleResponse) ProtoMessage() {}

func (x *UnloadModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModuleResponse.ProtoReflect.Descriptor instead.
func (*UnloadModuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *UnloadModuleResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // empty = all modules + daemon summary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatusRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ModuleStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State             string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Detail            map[string]string      `protobuf:"bytes,3,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Health            string                 `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"` // healthy | degraded | unhealthy
	HealthMessage     string                 `protobuf:"bytes,5,opt,name=health_message,json=healthMessage,proto3" json:"health_message,omitempty"`
	CheckedAtUnixNano int64                  `protobuf:"varint,6,opt,name=checked_at_unix_nano,json=checkedAtUnixNano,proto3" json:"checked_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModuleStatus) Reset() {
	*x = ModuleStatus{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStatus) ProtoMessage() {}

func (x *ModuleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStatus.ProtoReflect.Descriptor instead.
func (*ModuleStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *ModuleStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ModuleStatus) GetDetail() map[string]string {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *ModuleStatus) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ModuleStatus) GetHealthMessage() string {
	if x != nil {
		return x.HealthMessage
	}
	return ""
}

func (x *ModuleStatus) GetCheckedAtUnixNano() int64 {
	if x != nil {
		return x.CheckedAtUnixNano
	}
	return 0
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaemonVersion string                 `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	Modules       []*ModuleStatus        `protobuf:"bytes,2,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatusResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *GetStatusResponse) GetModules() []*ModuleStatus {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ListCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsRequest) Reset() {
	*x = ListCommandsRequest{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsRequest) ProtoMessage() {}

func (x *ListCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsRequest.ProtoReflect.Descriptor instead.
func (*ListCommandsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *ListCommandsRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type FlagSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shorthand     string                 `protobuf:"bytes,2,opt,name=shorthand,proto3" json:"shorthand,omitempty"`
	Usage         string                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Default       string                 `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // string | bool | int
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagSpec) Reset() {
	*x = FlagSpec{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagSpec) ProtoMessage() {}

func (x *FlagSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagSpec.ProtoReflect.Descriptor instead.
func (*FlagSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *FlagSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlagSpec) GetShorthand() string {
	if x != nil {
		return x.Shorthand
	}
	return ""
}

func (x *FlagSpec) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *FlagSpec) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *FlagSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CommandSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Use           string                 `protobuf:"bytes,2,opt,name=use,proto3" json:"use,omitempty"`
	Short         string                 `protobuf:"bytes,3,opt,name=short,proto3" json:"short,omitempty"`
	Flags         []*FlagSpec            `protobuf:"bytes,4,rep,name=flags,proto3" json:"flags,omitempty"`
	Subcommands   []*CommandSpec         `protobuf:"bytes,5,rep,name=subcommands,proto3" json:"subcommands,omitempty"`
	Tray          bool                   `protobuf:"varint,6,opt,name=tray,proto3" json:"tray,omitempty"`
	MinArgs       int32                  `protobuf:"varint,7,opt,name=min_args,json=minArgs,proto3" json:"min_args,omitempty"`
	MaxArgs       int32                  `protobuf:"varint,8,opt,name=max_args,json=maxArgs,proto3" json:"max_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandSpec) Reset() {
	*x = CommandSpec{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSpec) ProtoMessage() {}

func (x *CommandSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSpec.ProtoReflect.Descriptor instead.
func (*CommandSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *CommandSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandSpec) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *CommandSpec) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *CommandSpec) GetFlags() []*FlagSpec {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *CommandSpec) GetSubcommands() []*CommandSpec {
	if x != nil {
		return x.Subcommands
	}
	return nil
}

func (x *CommandSpec) GetTray() bool {
	if x != nil {
		return x.Tray
	}
	return false
}

func (x *CommandSpec) GetMinArgs() int32 {
	if x != nil {
		return x.MinArgs
	}
	return 0
}

func (x *CommandSpec) GetMaxArgs() int32 {
	if x != nil {
		return x.MaxArgs
	}
	return 0
}

type ModuleCommands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Commands      []*CommandSpec         `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleCommands) Reset() {
	*x = ModuleCommands{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleCommands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleCommands) ProtoMessage() {}

func (x *ModuleCommands) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleCommands.ProtoReflect.Descriptor instead.
func (*ModuleCommands) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *ModuleCommands) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ModuleCommands) GetCommands() []*CommandSpec {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ListCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*ModuleCommands      `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsResponse) Reset() {
	*x = ListCommandsResponse{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsResponse) ProtoMessage() {}

func (x *ListCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsResponse.ProtoReflect.Descriptor instead.
func (*ListCommandsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *ListCommandsResponse) GetModules() []*ModuleCommands {
	if x != nil {
		return x.Modules
	}
	return nil
}

type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Path          []string               `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"`
	Flags         map[string]string      `protobuf:"bytes,4,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Args          []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *DispatchRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *DispatchRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *DispatchRequest) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *DispatchRequest) GetFlags() map[string]string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *DispatchRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type DispatchChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`                      // human-readable text chunk
	Json          []byte                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`                          // machine-readable payload (final chunk)
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // meaningful on final chunk
	Final         bool                   `protobuf:"varint,4,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchChunk) Reset() {
	*x = DispatchChunk{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchChunk) ProtoMessage() {}

func (x *DispatchChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchChunk.ProtoReflect.Descriptor instead.
func (*DispatchChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *DispatchChunk) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *DispatchChunk) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *DispatchChunk) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *DispatchChunk) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type WatchEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"` // empty = all modules
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *WatchEventsRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *WatchEventsRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // state-changed | health | info | error
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	AtUnixNano    int64                  `protobuf:"varint,4,opt,name=at_unix_nano,json=atUnixNano,proto3" json:"at_unix_nano,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *Event) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetAtUnixNano() int64 {
	if x != nil {
		return x.AtUnixNano
	}
	return 0
}

func (x *Event) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type TailLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"` // empty = daemon
	Lines         int32                  `protobuf:"varint,3,opt,name=lines,proto3" json:"lines,omitempty"`  // initial backlog
	Follow        bool                   `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailLogsRequest) Reset() {
	*x = TailLogsRequest{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailLogsRequest) ProtoMessage() {}

func (x *TailLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailLogsRequest.ProtoReflect.Descriptor instead.
func (*TailLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *TailLogsRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *TailLogsRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *TailLogsRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

func (x *TailLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtUnixNano    int64                  `protobuf:"varint,1,opt,name=at_unix_nano,json=atUnixNano,proto3" json:"at_unix_nano,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{22}
}

func (x *LogLine) GetAtUnixNano() int64 {
	if x != nil {
		return x.AtUnixNano
	}
	return 0
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUpdateRequest) Reset() {
	*x = CheckUpdateRequest{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdateRequest) ProtoMessage() {}

func (x *CheckUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdateRequest.ProtoReflect.Descriptor instead.
func (*CheckUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *CheckUpdateRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type CheckUpdateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Available      bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	CurrentVersion string                 `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	LatestVersion  string                 `protobuf:"bytes,3,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckUpdateResponse) Reset() {
	*x = CheckUpdateResponse{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdateResponse) ProtoMessage() {}

func (x *CheckUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdateResponse.ProtoReflect.Descriptor instead.
func (*CheckUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{24}
}

func (x *CheckUpdateResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckUpdateResponse) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *CheckUpdateResponse) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

type ApplyUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyUpdateRequest) Reset() {
	*x = ApplyUpdateRequest{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyUpdateRequest) ProtoMessage() {}

func (x *ApplyUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyUpdateRequest.ProtoReflect.Descriptor instead.
func (*ApplyUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{25}
}

func (x *ApplyUpdateRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type ApplyUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyUpdateResponse) Reset() {
	*x = ApplyUpdateResponse{}
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyUpdateResponse) ProtoMessage() {}

func (x *ApplyUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyUpdateResponse.ProtoReflect.Descriptor instead.
func (*ApplyUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP(), []int{26}
}

func (x *ApplyUpdateResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ApplyUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_penguin_daemon_v1_daemon_proto protoreflect.FileDescriptor

const file_api_proto_penguin_daemon_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"(api/proto/penguin/daemon/v1/daemon.proto\x12\x11penguin.daemon.v1\"1\n" +
	"\x0eVersionRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"Y\n" +
	"\x0fVersionResponse\x12%\n" +
	"\x0edaemon_version\x18\x01 \x01(\tR\rdaemonVersion\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\"5\n" +
	"\x12ListModulesRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"\xba\x01\n" +
	"\rModuleSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1a\n" +
	"\bexternal\x18\x05 \x01(\bR\bexternal\x12'\n" +
	"\x0flicense_feature\x18\x06 \x01(\tR\x0elicenseFeature\"Q\n" +
	"\x13ListModulesResponse\x12:\n" +
	"\amodules\x18\x01 \x03(\v2 .penguin.daemon.v1.ModuleSummaryR\amodules\"H\n" +
	"\x11LoadModuleRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x12LoadModuleResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"J\n" +
	"\x13UnloadModuleRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x14UnloadModuleResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"G\n" +
	"\x10GetStatusRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa8\x02\n" +
	"\fModuleStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12C\n" +
	"\x06detail\x18\x03 \x03(\v2+.penguin.daemon.v1.ModuleStatus.DetailEntryR\x06detail\x12\x16\n" +
	"\x06health\x18\x04 \x01(\tR\x06health\x12%\n" +
	"\x0ehealth_message\x18\x05 \x01(\tR\rhealthMessage\x12/\n" +
	"\x14checked_at_unix_nano\x18\x06 \x01(\x03R\x11checkedAtUnixNano\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x11GetStatusResponse\x12%\n" +
	"\x0edaemon_version\x18\x01 \x01(\tR\rdaemonVersion\x129\n" +
	"\amodules\x18\x02 \x03(\v2\x1f.penguin.daemon.v1.ModuleStatusR\amodules\"6\n" +
	"\x13ListCommandsRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"\x80\x01\n" +
	"\bFlagSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tshorthand\x18\x02 \x01(\tR\tshorthand\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\tR\x05usage\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\x88\x02\n" +
	"\vCommandSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03use\x18\x02 \x01(\tR\x03use\x12\x14\n" +
	"\x05short\x18\x03 \x01(\tR\x05short\x121\n" +
	"\x05flags\x18\x04 \x03(\v2\x1b.penguin.daemon.v1.FlagSpecR\x05flags\x12@\n" +
	"\vsubcommands\x18\x05 \x03(\v2\x1e.penguin.daemon.v1.CommandSpecR\vsubcommands\x12\x12\n" +
	"\x04tray\x18\x06 \x01(\bR\x04tray\x12\x19\n" +
	"\bmin_args\x18\a \x01(\x05R\aminArgs\x12\x19\n" +
	"\bmax_args\x18\b \x01(\x05R\amaxArgs\"d\n" +
	"\x0eModuleCommands\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12:\n" +
	"\bcommands\x18\x02 \x03(\v2\x1e.penguin.daemon.v1.CommandSpecR\bcommands\"S\n" +
	"\x14ListCommandsResponse\x12;\n" +
	"\amodules\x18\x01 \x03(\v2!.penguin.daemon.v1.ModuleCommandsR\amodules\"\xf1\x01\n" +
	"\x0fDispatchRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x12\n" +
	"\x04path\x18\x03 \x03(\tR\x04path\x12C\n" +
	"\x05flags\x18\x04 \x03(\v2-.penguin.daemon.v1.DispatchRequest.FlagsEntryR\x05flags\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\rDispatchChunk\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x12\n" +
	"\x04json\x18\x02 \x01(\fR\x04json\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05final\x18\x04 \x01(\bR\x05final\"M\n" +
	"\x12WatchEventsRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\"\xe8\x01\n" +
	"\x05Event\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12 \n" +
	"\fat_unix_nano\x18\x04 \x01(\x03R\n" +
	"atUnixNano\x12<\n" +
	"\x06fields\x18\x05 \x03(\v2$.penguin.daemon.v1.Event.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\x0fTailLogsRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x14\n" +
	"\x05lines\x18\x03 \x01(\x05R\x05lines\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\"[\n" +
	"\aLogLine\x12 \n" +
	"\fat_unix_nano\x18\x01 \x01(\x03R\n" +
	"atUnixNano\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"5\n" +
	"\x12CheckUpdateRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"\x83\x01\n" +
	"\x13CheckUpdateResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\tR\x0ecurrentVersion\x12%\n" +
	"\x0elatest_version\x18\x03 \x01(\tR\rlatestVersion\"5\n" +
	"\x12ApplyUpdateRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"I\n" +
	"\x13ApplyUpdateResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xdd\a\n" +
	"\x06Daemon\x12P\n" +
	"\aVersion\x12!.penguin.daemon.v1.VersionRequest\x1a\".penguin.daemon.v1.VersionResponse\x12\\\n" +
	"\vListModules\x12%.penguin.daemon.v1.ListModulesRequest\x1a&.penguin.daemon.v1.ListModulesResponse\x12Y\n" +
	"\n" +
	"LoadModule\x12$.penguin.daemon.v1.LoadModuleRequest\x1a%.penguin.daemon.v1.LoadModuleResponse\x12_\n" +
	"\fUnloadModule\x12&.penguin.daemon.v1.UnloadModuleRequest\x1a'.penguin.daemon.v1.UnloadModuleResponse\x12V\n" +
	"\tGetStatus\x12#.penguin.daemon.v1.GetStatusRequest\x1a$.penguin.daemon.v1.GetStatusResponse\x12_\n" +
	"\fListCommands\x12&.penguin.daemon.v1.ListCommandsRequest\x1a'.penguin.daemon.v1.ListCommandsResponse\x12R\n" +
	"\bDispatch\x12\".penguin.daemon.v1.DispatchRequest\x1a .penguin.daemon.v1.DispatchChunk0\x01\x12P\n" +
	"\vWatchEvents\x12%.penguin.daemon.v1.WatchEventsRequest\x1a\x18.penguin.daemon.v1.Event0\x01\x12L\n" +
	"\bTailLogs\x12\".penguin.daemon.v1.TailLogsRequest\x1a\x1a.penguin.daemon.v1.LogLine0\x01\x12\\\n" +
	"\vCheckUpdate\x12%.penguin.daemon.v1.CheckUpdateRequest\x1a&.penguin.daemon.v1.CheckUpdateResponse\x12\\\n" +
	"\vApplyUpdate\x12%.penguin.daemon.v1.ApplyUpdateRequest\x1a&.penguin.daemon.v1.ApplyUpdateResponseBHZFgithub.com/penguintechinc/penguin/api/proto/penguin/daemon/v1;daemonv1b\x06proto3"

var (
	file_api_proto_penguin_daemon_v1_daemon_proto_rawDescOnce sync.Once
	file_api_proto_penguin_daemon_v1_daemon_proto_rawDescData []byte
)

func file_api_proto_penguin_daemon_v1_daemon_proto_rawDescGZIP() []byte {
	file_api_proto_penguin_daemon_v1_daemon_proto_rawDescOnce.Do(func() {
		file_api_proto_penguin_daemon_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_penguin_daemon_v1_daemon_proto_rawDesc), len(file_api_proto_penguin_daemon_v1_daemon_proto_rawDesc)))
	})
	return file_api_proto_penguin_daemon_v1_daemon_proto_rawDescData
}

var file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_api_proto_penguin_daemon_v1_daemon_proto_goTypes = []any{
	(*VersionRequest)(nil),       // 0: penguin.daemon.v1.VersionRequest
	(*VersionResponse)(nil),      // 1: penguin.daemon.v1.VersionResponse
	(*ListModulesRequest)(nil),   // 2: penguin.daemon.v1.ListModulesRequest
	(*ModuleSummary)(nil),        // 3: penguin.daemon.v1.ModuleSummary
	(*ListModulesResponse)(nil),  // 4: penguin.daemon.v1.ListModulesResponse
	(*LoadModuleRequest)(nil),    // 5: penguin.daemon.v1.LoadModuleRequest
	(*LoadModuleResponse)(nil),   // 6: penguin.daemon.v1.LoadModuleResponse
	(*UnloadModuleRequest)(nil),  // 7: penguin.daemon.v1.UnloadModuleRequest
	(*UnloadModuleResponse)(nil), // 8: penguin.daemon.v1.UnloadModuleResponse
	(*GetStatusRequest)(nil),     // 9: penguin.daemon.v1.GetStatusRequest
	(*ModuleStatus)(nil),         // 10: penguin.daemon.v1.ModuleStatus
	(*GetStatusResponse)(nil),    // 11: penguin.daemon.v1.GetStatusResponse
	(*ListCommandsRequest)(nil),  // 12: penguin.daemon.v1.ListCommandsRequest
	(*FlagSpec)(nil),             // 13: penguin.daemon.v1.FlagSpec
	(*CommandSpec)(nil),          // 14: penguin.daemon.v1.CommandSpec
	(*ModuleCommands)(nil),       // 15: penguin.daemon.v1.ModuleCommands
	(*ListCommandsResponse)(nil), // 16: penguin.daemon.v1.ListCommandsResponse
	(*DispatchRequest)(nil),      // 17: penguin.daemon.v1.DispatchRequest
	(*DispatchChunk)(nil),        // 18: penguin.daemon.v1.DispatchChunk
	(*WatchEventsRequest)(nil),   // 19: penguin.daemon.v1.WatchEventsRequest
	(*Event)(nil),                // 20: penguin.daemon.v1.Event
	(*TailLogsRequest)(nil),      // 21: penguin.daemon.v1.TailLogsRequest
	(*LogLine)(nil),              // 22: penguin.daemon.v1.LogLine
	(*CheckUpdateRequest)(nil),   // 23: penguin.daemon.v1.CheckUpdateRequest
	(*CheckUpdateResponse)(nil),  // 24: penguin.daemon.v1.CheckUpdateResponse
	(*ApplyUpdateRequest)(nil),   // 25: penguin.daemon.v1.ApplyUpdateRequest
	(*ApplyUpdateResponse)(nil),  // 26: penguin.daemon.v1.ApplyUpdateResponse
	nil,                          // 27: penguin.daemon.v1.ModuleStatus.DetailEntry
	nil,                          // 28: penguin.daemon.v1.DispatchRequest.FlagsEntry
	nil,                          // 29: penguin.daemon.v1.Event.FieldsEntry
}
var file_api_proto_penguin_daemon_v1_daemon_proto_depIdxs = []int32{
	3,  // 0: penguin.daemon.v1.ListModulesResponse.modules:type_name -> penguin.daemon.v1.ModuleSummary
	27, // 1: penguin.daemon.v1.ModuleStatus.detail:type_name -> penguin.daemon.v1.ModuleStatus.DetailEntry
	10, // 2: penguin.daemon.v1.GetStatusResponse.modules:type_name -> penguin.daemon.v1.ModuleStatus
	13, // 3: penguin.daemon.v1.CommandSpec.flags:type_name -> penguin.daemon.v1.FlagSpec
	14, // 4: penguin.daemon.v1.CommandSpec.subcommands:type_name -> penguin.daemon.v1.CommandSpec
	14, // 5: penguin.daemon.v1.ModuleCommands.commands:type_name -> penguin.daemon.v1.CommandSpec
	15, // 6: penguin.daemon.v1.ListCommandsResponse.modules:type_name -> penguin.daemon.v1.ModuleCommands
	28, // 7: penguin.daemon.v1.DispatchRequest.flags:type_name -> penguin.daemon.v1.DispatchRequest.FlagsEntry
	29, // 8: penguin.daemon.v1.Event.fields:type_name -> penguin.daemon.v1.Event.FieldsEntry
	0,  // 9: penguin.daemon.v1.Daemon.Version:input_type -> penguin.daemon.v1.VersionRequest
	2,  // 10: penguin.daemon.v1.Daemon.ListModules:input_type -> penguin.daemon.v1.ListModulesRequest
	5,  // 11: penguin.daemon.v1.Daemon.LoadModule:input_type -> penguin.daemon.v1.LoadModuleRequest
	7,  // 12: penguin.daemon.v1.Daemon.UnloadModule:input_type -> penguin.daemon.v1.UnloadModuleRequest
	9,  // 13: penguin.daemon.v1.Daemon.GetStatus:input_type -> penguin.daemon.v1.GetStatusRequest
	12, // 14: penguin.daemon.v1.Daemon.ListCommands:input_type -> penguin.daemon.v1.ListCommandsRequest
	17, // 15: penguin.daemon.v1.Daemon.Dispatch:input_type -> penguin.daemon.v1.DispatchRequest
	19, // 16: penguin.daemon.v1.Daemon.WatchEvents:input_type -> penguin.daemon.v1.WatchEventsRequest
	21, // 17: penguin.daemon.v1.Daemon.TailLogs:input_type -> penguin.daemon.v1.TailLogsRequest
	23, // 18: penguin.daemon.v1.Daemon.CheckUpdate:input_type -> penguin.daemon.v1.CheckUpdateRequest
	25, // 19: penguin.daemon.v1.Daemon.ApplyUpdate:input_type -> penguin.daemon.v1.ApplyUpdateRequest
	1,  // 20: penguin.daemon.v1.Daemon.Version:output_type -> penguin.daemon.v1.VersionResponse
	4,  // 21: penguin.daemon.v1.Daemon.ListModules:output_type -> penguin.daemon.v1.ListModulesResponse
	6,  // 22: penguin.daemon.v1.Daemon.LoadModule:output_type -> penguin.daemon.v1.LoadModuleResponse
	8,  // 23: penguin.daemon.v1.Daemon.UnloadModule:output_type -> penguin.daemon.v1.UnloadModuleResponse
	11, // 24: penguin.daemon.v1.Daemon.GetStatus:output_type -> penguin.daemon.v1.GetStatusResponse
	16, // 25: penguin.daemon.v1.Daemon.ListCommands:output_type -> penguin.daemon.v1.ListCommandsResponse
	18, // 26: penguin.daemon.v1.Daemon.Dispatch:output_type -> penguin.daemon.v1.DispatchChunk
	20, // 27: penguin.daemon.v1.Daemon.WatchEvents:output_type -> penguin.daemon.v1.Event
	22, // 28: penguin.daemon.v1.Daemon.TailLogs:output_type -> penguin.daemon.v1.LogLine
	24, // 29: penguin.daemon.v1.Daemon.CheckUpdate:output_type -> penguin.daemon.v1.CheckUpdateResponse
	26, // 30: penguin.daemon.v1.Daemon.ApplyUpdate:output_type -> penguin.daemon.v1.ApplyUpdateResponse
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_penguin_daemon_v1_daemon_proto_init() }
func file_api_proto_penguin_daemon_v1_daemon_proto_init() {
	if File_api_proto_penguin_daemon_v1_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_penguin_daemon_v1_daemon_proto_rawDesc), len(file_api_proto_penguin_daemon_v1_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_penguin_daemon_v1_daemon_proto_goTypes,
		DependencyIndexes: file_api_proto_penguin_daemon_v1_daemon_proto_depIdxs,
		MessageInfos:      file_api_proto_penguin_daemon_v1_daemon_proto_msgTypes,
	}.Build()
	File_api_proto_penguin_daemon_v1_daemon_proto = out.File
	file_api_proto_penguin_daemon_v1_daemon_proto_goTypes = nil
	file_api_proto_penguin_daemon_v1_daemon_proto_depIdxs = nil
}
