// Module is the plugin-side gRPC contract for external modules.
// It mirrors sdk.Module 1:1 across the go-plugin boundary.
// The plugin implements ModuleService; the daemon implements HostService.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: pkg/sdk/proto/penguin/sdk/v1/module.proto

package sdkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{0}
}

func (x *InfoRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type InfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LicenseFeature string                 `protobuf:"bytes,4,opt,name=license_feature,json=licenseFeature,proto3" json:"license_feature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InfoResponse) GetLicenseFeature() string {
	if x != nil {
		return x.LicenseFeature
	}
	return ""
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{3}
}

func (x *InitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{4}
}

func (x *StartRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{5}
}

func (x *StartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{6}
}

func (x *StopRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{7}
}

func (x *StopResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{8}
}

func (x *StatusRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Detail        map[string]string      `protobuf:"bytes,2,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusResponse) GetDetail() map[string]string {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *StatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{10}
}

func (x *HealthRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type HealthResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Level             int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"` // 0=healthy, 1=degraded, 2=unhealthy
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CheckedAtUnixNano int64                  `protobuf:"varint,3,opt,name=checked_at_unix_nano,json=checkedAtUnixNano,proto3" json:"checked_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetCheckedAtUnixNano() int64 {
	if x != nil {
		return x.CheckedAtUnixNano
	}
	return 0
}

type CommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandsRequest) Reset() {
	*x = CommandsRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandsRequest) ProtoMessage() {}

func (x *CommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandsRequest.ProtoReflect.Descriptor instead.
func (*CommandsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{12}
}

func (x *CommandsRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type FlagSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shorthand     string                 `protobuf:"bytes,2,opt,name=shorthand,proto3" json:"shorthand,omitempty"`
	Usage         string                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Default       string                 `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // "string" | "bool" | "int"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagSpec) Reset() {
	*x = FlagSpec{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagSpec) ProtoMessage() {}

func (x *FlagSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagSpec.ProtoReflect.Descriptor instead.
func (*FlagSpec) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{13}
}

func (x *FlagSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlagSpec) GetShorthand() string {
	if x != nil {
		return x.Shorthand
	}
	return ""
}

func (x *FlagSpec) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *FlagSpec) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *FlagSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CommandSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Use           string                 `protobuf:"bytes,2,opt,name=use,proto3" json:"use,omitempty"`
	Short         string                 `protobuf:"bytes,3,opt,name=short,proto3" json:"short,omitempty"`
	Flags         []*FlagSpec            `protobuf:"bytes,4,rep,name=flags,proto3" json:"flags,omitempty"`
	Subcommands   []*CommandSpec         `protobuf:"bytes,5,rep,name=subcommands,proto3" json:"subcommands,omitempty"`
	Tray          bool                   `protobuf:"varint,6,opt,name=tray,proto3" json:"tray,omitempty"`
	MinArgs       int32                  `protobuf:"varint,7,opt,name=min_args,json=minArgs,proto3" json:"min_args,omitempty"`
	MaxArgs       int32                  `protobuf:"varint,8,opt,name=max_args,json=maxArgs,proto3" json:"max_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandSpec) Reset() {
	*x = CommandSpec{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSpec) ProtoMessage() {}

func (x *CommandSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSpec.ProtoReflect.Descriptor instead.
func (*CommandSpec) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{14}
}

func (x *CommandSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandSpec) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *CommandSpec) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *CommandSpec) GetFlags() []*FlagSpec {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *CommandSpec) GetSubcommands() []*CommandSpec {
	if x != nil {
		return x.Subcommands
	}
	return nil
}

func (x *CommandSpec) GetTray() bool {
	if x != nil {
		return x.Tray
	}
	return false
}

func (x *CommandSpec) GetMinArgs() int32 {
	if x != nil {
		return x.MinArgs
	}
	return 0
}

func (x *CommandSpec) GetMaxArgs() int32 {
	if x != nil {
		return x.MaxArgs
	}
	return 0
}

type CommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CommandSpec         `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandsResponse) Reset() {
	*x = CommandsResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandsResponse) ProtoMessage() {}

func (x *CommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandsResponse.ProtoReflect.Descriptor instead.
func (*CommandsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{15}
}

func (x *CommandsResponse) GetCommands() []*CommandSpec {
	if x != nil {
		return x.Commands
	}
	return nil
}

type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Path          []string               `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	Flags         map[string]string      `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{16}
}

func (x *DispatchRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *DispatchRequest) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *DispatchRequest) GetFlags() map[string]string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *DispatchRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type DispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Json          []byte                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{17}
}

func (x *DispatchResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *DispatchResponse) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *DispatchResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *DispatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfigSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaRequest) Reset() {
	*x = ConfigSchemaRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaRequest) ProtoMessage() {}

func (x *ConfigSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaRequest.ProtoReflect.Descriptor instead.
func (*ConfigSchemaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{18}
}

func (x *ConfigSchemaRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type ConfigSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        []byte                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // JSON Schema bytes, or empty if no configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaResponse) Reset() {
	*x = ConfigSchemaResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaResponse) ProtoMessage() {}

func (x *ConfigSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaResponse.ProtoReflect.Descriptor instead.
func (*ConfigSchemaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{19}
}

func (x *ConfigSchemaResponse) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // "debug" | "info" | "warn" | "error"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{20}
}

func (x *LogRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{21}
}

type SecretsGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretsGetRequest) Reset() {
	*x = SecretsGetRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsGetRequest) ProtoMessage() {}

func (x *SecretsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretsGetRequest.ProtoReflect.Descriptor instead.
func (*SecretsGetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{22}
}

func (x *SecretsGetRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *SecretsGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SecretsGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Set if key not found or other error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretsGetResponse) Reset() {
	*x = SecretsGetResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsGetResponse) ProtoMessage() {}

func (x *SecretsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretsGetResponse.ProtoReflect.Descriptor instead.
func (*SecretsGetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{23}
}

func (x *SecretsGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SecretsGetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SecretsSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretsSetRequest) Reset() {
	*x = SecretsSetRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsSetRequest) ProtoMessage() {}

func (x *SecretsSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretsSetRequest.ProtoReflect.Descriptor instead.
func (*SecretsSetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{24}
}

func (x *SecretsSetRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *SecretsSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SecretsSetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SecretsSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretsSetResponse) Reset() {
	*x = SecretsSetResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsSetResponse) ProtoMessage() {}

func (x *SecretsSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretsSetResponse.ProtoReflect.Descriptor instead.
func (*SecretsSetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{25}
}

func (x *SecretsSetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SecretsDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretsDeleteRequest) Reset() {
	*x = SecretsDeleteRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsDeleteRequest) ProtoMessage() {}

func (x *SecretsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretsDeleteRequest.ProtoReflect.Descriptor instead.
func (*SecretsDeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{26}
}

func (x *SecretsDeleteRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *SecretsDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SecretsDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretsDeleteResponse) Reset() {
	*x = SecretsDeleteResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsDeleteResponse) ProtoMessage() {}

func (x *SecretsDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretsDeleteResponse.ProtoReflect.Descriptor instead.
func (*SecretsDeleteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{27}
}

func (x *SecretsDeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LicenseFeatureEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseFeatureEnabledRequest) Reset() {
	*x = LicenseFeatureEnabledRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseFeatureEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseFeatureEnabledRequest) ProtoMessage() {}

func (x *LicenseFeatureEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseFeatureEnabledRequest.ProtoReflect.Descriptor instead.
func (*LicenseFeatureEnabledRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{28}
}

func (x *LicenseFeatureEnabledRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *LicenseFeatureEnabledRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LicenseFeatureEnabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseFeatureEnabledResponse) Reset() {
	*x = LicenseFeatureEnabledResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseFeatureEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseFeatureEnabledResponse) ProtoMessage() {}

func (x *LicenseFeatureEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseFeatureEnabledResponse.ProtoReflect.Descriptor instead.
func (*LicenseFeatureEnabledResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{29}
}

func (x *LicenseFeatureEnabledResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type LicenseTierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseTierRequest) Reset() {
	*x = LicenseTierRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseTierRequest) ProtoMessage() {}

func (x *LicenseTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseTierRequest.ProtoReflect.Descriptor instead.
func (*LicenseTierRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{30}
}

func (x *LicenseTierRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type LicenseTierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          string                 `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"` // "" | "free" | "professional" | "enterprise"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseTierResponse) Reset() {
	*x = LicenseTierResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseTierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseTierResponse) ProtoMessage() {}

func (x *LicenseTierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseTierResponse.ProtoReflect.Descriptor instead.
func (*LicenseTierResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{31}
}

func (x *LicenseTierResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

type DataDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataDirRequest) Reset() {
	*x = DataDirRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDirRequest) ProtoMessage() {}

func (x *DataDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDirRequest.ProtoReflect.Descriptor instead.
func (*DataDirRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{32}
}

func (x *DataDirRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type DataDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataDirResponse) Reset() {
	*x = DataDirResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDirResponse) ProtoMessage() {}

func (x *DataDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDirResponse.ProtoReflect.Descriptor instead.
func (*DataDirResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{33}
}

func (x *DataDirResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{34}
}

func (x *ConfigRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"` // Raw YAML bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{35}
}

func (x *ConfigResponse) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type PublishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "state-changed" | "health" | "info" | "error"
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	AtUnixNano    int64                  `protobuf:"varint,5,opt,name=at_unix_nano,json=atUnixNano,proto3" json:"at_unix_nano,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{36}
}

func (x *PublishEventRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PublishEventRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *PublishEventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PublishEventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PublishEventRequest) GetAtUnixNano() int64 {
	if x != nil {
		return x.AtUnixNano
	}
	return 0
}

func (x *PublishEventRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP(), []int{37}
}

var File_pkg_sdk_proto_penguin_sdk_v1_module_proto protoreflect.FileDescriptor

const file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDesc = "" +
	"\n" +
	")pkg/sdk/proto/penguin/sdk/v1/module.proto\x12\x0epenguin.sdk.v1\".\n" +
	"\vInfoRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"\x87\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0flicense_feature\x18\x04 \x01(\tR\x0elicenseFeature\".\n" +
	"\vInitRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"$\n" +
	"\fInitResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"/\n" +
	"\fStartRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"%\n" +
	"\rStartResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\".\n" +
	"\vStopRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"$\n" +
	"\fStopResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"0\n" +
	"\rStatusRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"\xbb\x01\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12B\n" +
	"\x06detail\x18\x02 \x03(\v2*.penguin.sdk.v1.StatusResponse.DetailEntryR\x06detail\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\rHealthRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"q\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x14checked_at_unix_nano\x18\x03 \x01(\x03R\x11checkedAtUnixNano\"2\n" +
	"\x0fCommandsRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"\x80\x01\n" +
	"\bFlagSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tshorthand\x18\x02 \x01(\tR\tshorthand\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\tR\x05usage\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\x82\x02\n" +
	"\vCommandSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03use\x18\x02 \x01(\tR\x03use\x12\x14\n" +
	"\x05short\x18\x03 \x01(\tR\x05short\x12.\n" +
	"\x05flags\x18\x04 \x03(\v2\x18.penguin.sdk.v1.FlagSpecR\x05flags\x12=\n" +
	"\vsubcommands\x18\x05 \x03(\v2\x1b.penguin.sdk.v1.CommandSpecR\vsubcommands\x12\x12\n" +
	"\x04tray\x18\x06 \x01(\bR\x04tray\x12\x19\n" +
	"\bmin_args\x18\a \x01(\x05R\aminArgs\x12\x19\n" +
	"\bmax_args\x18\b \x01(\x05R\amaxArgs\"K\n" +
	"\x10CommandsResponse\x127\n" +
	"\bcommands\x18\x01 \x03(\v2\x1b.penguin.sdk.v1.CommandSpecR\bcommands\"\xd6\x01\n" +
	"\x0fDispatchRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04path\x18\x02 \x03(\tR\x04path\x12@\n" +
	"\x05flags\x18\x03 \x03(\v2*.penguin.sdk.v1.DispatchRequest.FlagsEntryR\x05flags\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x10DispatchResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x12\n" +
	"\x04json\x18\x02 \x01(\fR\x04json\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"6\n" +
	"\x13ConfigSchemaRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\".\n" +
	"\x14ConfigSchemaResponse\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\fR\x06schema\"\xd8\x01\n" +
	"\n" +
	"LogRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12>\n" +
	"\x06fields\x18\x04 \x03(\v2&.penguin.sdk.v1.LogRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\r\n" +
	"\vLogResponse\"F\n" +
	"\x11SecretsGetRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"@\n" +
	"\x12SecretsGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\\\n" +
	"\x11SecretsSetRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"*\n" +
	"\x12SecretsSetResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"I\n" +
	"\x14SecretsDeleteRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"-\n" +
	"\x15SecretsDeleteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"Q\n" +
	"\x1cLicenseFeatureEnabledRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"9\n" +
	"\x1dLicenseFeatureEnabledResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"5\n" +
	"\x12LicenseTierRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\")\n" +
	"\x13LicenseTierResponse\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\tR\x04tier\"1\n" +
	"\x0eDataDirRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"%\n" +
	"\x0fDataDirResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"0\n" +
	"\rConfigRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\"(\n" +
	"\x0eConfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\"\xa2\x02\n" +
	"\x13PublishEventRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12 \n" +
	"\fat_unix_nano\x18\x05 \x01(\x03R\n" +
	"atUnixNano\x12G\n" +
	"\x06fields\x18\x06 \x03(\v2/.penguin.sdk.v1.PublishEventRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14PublishEventResponse2\xa9\x05\n" +
	"\rModuleService\x12A\n" +
	"\x04Info\x12\x1b.penguin.sdk.v1.InfoRequest\x1a\x1c.penguin.sdk.v1.InfoResponse\x12A\n" +
	"\x04Init\x12\x1b.penguin.sdk.v1.InitRequest\x1a\x1c.penguin.sdk.v1.InitResponse\x12D\n" +
	"\x05Start\x12\x1c.penguin.sdk.v1.StartRequest\x1a\x1d.penguin.sdk.v1.StartResponse\x12A\n" +
	"\x04Stop\x12\x1b.penguin.sdk.v1.StopRequest\x1a\x1c.penguin.sdk.v1.StopResponse\x12G\n" +
	"\x06Status\x12\x1d.penguin.sdk.v1.StatusRequest\x1a\x1e.penguin.sdk.v1.StatusResponse\x12G\n" +
	"\x06Health\x12\x1d.penguin.sdk.v1.HealthRequest\x1a\x1e.penguin.sdk.v1.HealthResponse\x12M\n" +
	"\bCommands\x12\x1f.penguin.sdk.v1.CommandsRequest\x1a .penguin.sdk.v1.CommandsResponse\x12M\n" +
	"\bDispatch\x12\x1f.penguin.sdk.v1.DispatchRequest\x1a .penguin.sdk.v1.DispatchResponse\x12Y\n" +
	"\fConfigSchema\x12#.penguin.sdk.v1.ConfigSchemaRequest\x1a$.penguin.sdk.v1.ConfigSchemaResponse2\x93\x06\n" +
	"\vHostService\x12>\n" +
	"\x03Log\x12\x1a.penguin.sdk.v1.LogRequest\x1a\x1b.penguin.sdk.v1.LogResponse\x12S\n" +
	"\n" +
	"SecretsGet\x12!.penguin.sdk.v1.SecretsGetRequest\x1a\".penguin.sdk.v1.SecretsGetResponse\x12S\n" +
	"\n" +
	"SecretsSet\x12!.penguin.sdk.v1.SecretsSetRequest\x1a\".penguin.sdk.v1.SecretsSetResponse\x12\\\n" +
	"\rSecretsDelete\x12$.penguin.sdk.v1.SecretsDeleteRequest\x1a%.penguin.sdk.v1.SecretsDeleteResponse\x12t\n" +
	"\x15LicenseFeatureEnabled\x12,.penguin.sdk.v1.LicenseFeatureEnabledRequest\x1a-.penguin.sdk.v1.LicenseFeatureEnabledResponse\x12V\n" +
	"\vLicenseTier\x12\".penguin.sdk.v1.LicenseTierRequest\x1a#.penguin.sdk.v1.LicenseTierResponse\x12J\n" +
	"\aDataDir\x12\x1e.penguin.sdk.v1.DataDirRequest\x1a\x1f.penguin.sdk.v1.DataDirResponse\x12G\n" +
	"\x06Config\x12\x1d.penguin.sdk.v1.ConfigRequest\x1a\x1e.penguin.sdk.v1.ConfigResponse\x12Y\n" +
	"\fPublishEvent\x12#.penguin.sdk.v1.PublishEventRequest\x1a$.penguin.sdk.v1.PublishEventResponseBFZDgithub.com/penguintechinc/penguin/pkg/sdk/proto/penguin/sdk/v1;sdkv1b\x06proto3"

var (
	file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescOnce sync.Once
	file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescData []byte
)

func file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescGZIP() []byte {
	file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescOnce.Do(func() {
		file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDesc), len(file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDesc)))
	})
	return file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDescData
}

var file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_pkg_sdk_proto_penguin_sdk_v1_module_proto_goTypes = []any{
	(*InfoRequest)(nil),                   // 0: penguin.sdk.v1.InfoRequest
	(*InfoResponse)(nil),                  // 1: penguin.sdk.v1.InfoResponse
	(*InitRequest)(nil),                   // 2: penguin.sdk.v1.InitRequest
	(*InitResponse)(nil),                  // 3: penguin.sdk.v1.InitResponse
	(*StartRequest)(nil),                  // 4: penguin.sdk.v1.StartRequest
	(*StartResponse)(nil),                 // 5: penguin.sdk.v1.StartResponse
	(*StopRequest)(nil),                   // 6: penguin.sdk.v1.StopRequest
	(*StopResponse)(nil),                  // 7: penguin.sdk.v1.StopResponse
	(*StatusRequest)(nil),                 // 8: penguin.sdk.v1.StatusRequest
	(*StatusResponse)(nil),                // 9: penguin.sdk.v1.StatusResponse
	(*HealthRequest)(nil),                 // 10: penguin.sdk.v1.HealthRequest
	(*HealthResponse)(nil),                // 11: penguin.sdk.v1.HealthResponse
	(*CommandsRequest)(nil),               // 12: penguin.sdk.v1.CommandsRequest
	(*FlagSpec)(nil),                      // 13: penguin.sdk.v1.FlagSpec
	(*CommandSpec)(nil),                   // 14: penguin.sdk.v1.CommandSpec
	(*CommandsResponse)(nil),              // 15: penguin.sdk.v1.CommandsResponse
	(*DispatchRequest)(nil),               // 16: penguin.sdk.v1.DispatchRequest
	(*DispatchResponse)(nil),              // 17: penguin.sdk.v1.DispatchResponse
	(*ConfigSchemaRequest)(nil),           // 18: penguin.sdk.v1.ConfigSchemaRequest
	(*ConfigSchemaResponse)(nil),          // 19: penguin.sdk.v1.ConfigSchemaResponse
	(*LogRequest)(nil),                    // 20: penguin.sdk.v1.LogRequest
	(*LogResponse)(nil),                   // 21: penguin.sdk.v1.LogResponse
	(*SecretsGetRequest)(nil),             // 22: penguin.sdk.v1.SecretsGetRequest
	(*SecretsGetResponse)(nil),            // 23: penguin.sdk.v1.SecretsGetResponse
	(*SecretsSetRequest)(nil),             // 24: penguin.sdk.v1.SecretsSetRequest
	(*SecretsSetResponse)(nil),            // 25: penguin.sdk.v1.SecretsSetResponse
	(*SecretsDeleteRequest)(nil),          // 26: penguin.sdk.v1.SecretsDeleteRequest
	(*SecretsDeleteResponse)(nil),         // 27: penguin.sdk.v1.SecretsDeleteResponse
	(*LicenseFeatureEnabledRequest)(nil),  // 28: penguin.sdk.v1.LicenseFeatureEnabledRequest
	(*LicenseFeatureEnabledResponse)(nil), // 29: penguin.sdk.v1.LicenseFeatureEnabledResponse
	(*LicenseTierRequest)(nil),            // 30: penguin.sdk.v1.LicenseTierRequest
	(*LicenseTierResponse)(nil),           // 31: penguin.sdk.v1.LicenseTierResponse
	(*DataDirRequest)(nil),                // 32: penguin.sdk.v1.DataDirRequest
	(*DataDirResponse)(nil),               // 33: penguin.sdk.v1.DataDirResponse
	(*ConfigRequest)(nil),                 // 34: penguin.sdk.v1.ConfigRequest
	(*ConfigResponse)(nil),                // 35: penguin.sdk.v1.ConfigResponse
	(*PublishEventRequest)(nil),           // 36: penguin.sdk.v1.PublishEventRequest
	(*PublishEventResponse)(nil),          // 37: penguin.sdk.v1.PublishEventResponse
	nil,                                   // 38: penguin.sdk.v1.StatusResponse.DetailEntry
	nil,                                   // 39: penguin.sdk.v1.DispatchRequest.FlagsEntry
	nil,                                   // 40: penguin.sdk.v1.LogRequest.FieldsEntry
	nil,                                   // 41: penguin.sdk.v1.PublishEventRequest.FieldsEntry
}
var file_pkg_sdk_proto_penguin_sdk_v1_module_proto_depIdxs = []int32{
	38, // 0: penguin.sdk.v1.StatusResponse.detail:type_name -> penguin.sdk.v1.StatusResponse.DetailEntry
	13, // 1: penguin.sdk.v1.CommandSpec.flags:type_name -> penguin.sdk.v1.FlagSpec
	14, // 2: penguin.sdk.v1.CommandSpec.subcommands:type_name -> penguin.sdk.v1.CommandSpec
	14, // 3: penguin.sdk.v1.CommandsResponse.commands:type_name -> penguin.sdk.v1.CommandSpec
	39, // 4: penguin.sdk.v1.DispatchRequest.flags:type_name -> penguin.sdk.v1.DispatchRequest.FlagsEntry
	40, // 5: penguin.sdk.v1.LogRequest.fields:type_name -> penguin.sdk.v1.LogRequest.FieldsEntry
	41, // 6: penguin.sdk.v1.PublishEventRequest.fields:type_name -> penguin.sdk.v1.PublishEventRequest.FieldsEntry
	0,  // 7: penguin.sdk.v1.ModuleService.Info:input_type -> penguin.sdk.v1.InfoRequest
	2,  // 8: penguin.sdk.v1.ModuleService.Init:input_type -> penguin.sdk.v1.InitRequest
	4,  // 9: penguin.sdk.v1.ModuleService.Start:input_type -> penguin.sdk.v1.StartRequest
	6,  // 10: penguin.sdk.v1.ModuleService.Stop:input_type -> penguin.sdk.v1.StopRequest
	8,  // 11: penguin.sdk.v1.ModuleService.Status:input_type -> penguin.sdk.v1.StatusRequest
	10, // 12: penguin.sdk.v1.ModuleService.Health:input_type -> penguin.sdk.v1.HealthRequest
	12, // 13: penguin.sdk.v1.ModuleService.Commands:input_type -> penguin.sdk.v1.CommandsRequest
	16, // 14: penguin.sdk.v1.ModuleService.Dispatch:input_type -> penguin.sdk.v1.DispatchRequest
	18, // 15: penguin.sdk.v1.ModuleService.ConfigSchema:input_type -> penguin.sdk.v1.ConfigSchemaRequest
	20, // 16: penguin.sdk.v1.HostService.Log:input_type -> penguin.sdk.v1.LogRequest
	22, // 17: penguin.sdk.v1.HostService.SecretsGet:input_type -> penguin.sdk.v1.SecretsGetRequest
	24, // 18: penguin.sdk.v1.HostService.SecretsSet:input_type -> penguin.sdk.v1.SecretsSetRequest
	26, // 19: penguin.sdk.v1.HostService.SecretsDelete:input_type -> penguin.sdk.v1.SecretsDeleteRequest
	28, // 20: penguin.sdk.v1.HostService.LicenseFeatureEnabled:input_type -> penguin.sdk.v1.LicenseFeatureEnabledRequest
	30, // 21: penguin.sdk.v1.HostService.LicenseTier:input_type -> penguin.sdk.v1.LicenseTierRequest
	32, // 22: penguin.sdk.v1.HostService.DataDir:input_type -> penguin.sdk.v1.DataDirRequest
	34, // 23: penguin.sdk.v1.HostService.Config:input_type -> penguin.sdk.v1.ConfigRequest
	36, // 24: penguin.sdk.v1.HostService.PublishEvent:input_type -> penguin.sdk.v1.PublishEventRequest
	1,  // 25: penguin.sdk.v1.ModuleService.Info:output_type -> penguin.sdk.v1.InfoResponse
	3,  // 26: penguin.sdk.v1.ModuleService.Init:output_type -> penguin.sdk.v1.InitResponse
	5,  // 27: penguin.sdk.v1.ModuleService.Start:output_type -> penguin.sdk.v1.StartResponse
	7,  // 28: penguin.sdk.v1.ModuleService.Stop:output_type -> penguin.sdk.v1.StopResponse
	9,  // 29: penguin.sdk.v1.ModuleService.Status:output_type -> penguin.sdk.v1.StatusResponse
	11, // 30: penguin.sdk.v1.ModuleService.Health:output_type -> penguin.sdk.v1.HealthResponse
	15, // 31: penguin.sdk.v1.ModuleService.Commands:output_type -> penguin.sdk.v1.CommandsResponse
	17, // 32: penguin.sdk.v1.ModuleService.Dispatch:output_type -> penguin.sdk.v1.DispatchResponse
	19, // 33: penguin.sdk.v1.ModuleService.ConfigSchema:output_type -> penguin.sdk.v1.ConfigSchemaResponse
	21, // 34: penguin.sdk.v1.HostService.Log:output_type -> penguin.sdk.v1.LogResponse
	23, // 35: penguin.sdk.v1.HostService.SecretsGet:output_type -> penguin.sdk.v1.SecretsGetResponse
	25, // 36: penguin.sdk.v1.HostService.SecretsSet:output_type -> penguin.sdk.v1.SecretsSetResponse
	27, // 37: penguin.sdk.v1.HostService.SecretsDelete:output_type -> penguin.sdk.v1.SecretsDeleteResponse
	29, // 38: penguin.sdk.v1.HostService.LicenseFeatureEnabled:output_type -> penguin.sdk.v1.LicenseFeatureEnabledResponse
	31, // 39: penguin.sdk.v1.HostService.LicenseTier:output_type -> penguin.sdk.v1.LicenseTierResponse
	33, // 40: penguin.sdk.v1.HostService.DataDir:output_type -> penguin.sdk.v1.DataDirResponse
	35, // 41: penguin.sdk.v1.HostService.Config:output_type -> penguin.sdk.v1.ConfigResponse
	37, // 42: penguin.sdk.v1.HostService.PublishEvent:output_type -> penguin.sdk.v1.PublishEventResponse
	25, // [25:43] is the sub-list for method output_type
	7,  // [7:25] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_sdk_proto_penguin_sdk_v1_module_proto_init() }
func file_pkg_sdk_proto_penguin_sdk_v1_module_proto_init() {
	if File_pkg_sdk_proto_penguin_sdk_v1_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDesc), len(file_pkg_sdk_proto_penguin_sdk_v1_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_sdk_proto_penguin_sdk_v1_module_proto_goTypes,
		DependencyIndexes: file_pkg_sdk_proto_penguin_sdk_v1_module_proto_depIdxs,
		MessageInfos:      file_pkg_sdk_proto_penguin_sdk_v1_module_proto_msgTypes,
	}.Build()
	File_pkg_sdk_proto_penguin_sdk_v1_module_proto = out.File
	file_pkg_sdk_proto_penguin_sdk_v1_module_proto_goTypes = nil
	file_pkg_sdk_proto_penguin_sdk_v1_module_proto_depIdxs = nil
}
