---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: project-template-beta

namespace: project-template

namePrefix: beta-

commonLabels:
  environment: beta

bases:
- ../../base

replicas:
- name: flask-backend
  count: 2
- name: go-backend
  count: 2
- name: webui
  count: 2

images:
- name: flask-backend
  newName: ghcr.io/penguintechinc/penguin/flask-backend
  newTag: latest
- name: go-backend
  newName: ghcr.io/penguintechinc/penguin/go-backend
  newTag: latest
- name: webui
  newName: ghcr.io/penguintechinc/penguin/webui
  newTag: latest

configMapGenerator:
- name: project-template-config
  behavior: merge
  literals:
  - LOG_LEVEL=INFO
  - RELEASE_MODE=false
